In [1]:
import numpy as np
import tensorflow as tf

import pandas as pd
import tensorflow_recommenders as tfrs
import tensorflow_datasets as tfds

In [12]:
rating = pd.read_csv("D:\My Docs\PICT CS\SE_21_22\PBL\DVSAM\Src\JustTrain.csv")

In [15]:
rests = pd.read_csv("rest_titles.csv")

In [17]:
rests['rest_name'] = pd.Categorical(rests['rest_name'])
rests['rest_name'] = rests['rest_name'].cat.codes

In [18]:
rating = tf.convert_to_tensor(rating)
rests = tf.convert_to_tensor(rests)

In [9]:
rating.to_csv('FinalTraining.csv')

In [12]:
rating

,user_id,index,loc,sponsor,votes,rating,charge,cuisine,alcohol,veg,vegan,sugarfree,buff
0,0,10962,Dhanori,Quick Bites,4,2.8,200.0,South Indian,0,1,0,0,0
1,0,11679,Kothrud,Quick Bites,26,3.6,500.0,North Indian,0,0,0,0,0
2,0,6863,Shivaji Nagar,Takeaway,0,0.0,0.0,Bakery,0,0,0,0,0
3,0,2354,Chandan Nagar,Casual Dining,32,3.4,600.0,Chinese,0,1,0,0,0
4,0,3429,Pimpri,Quick Bites,168,4.3,350.0,Sandwich,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19963,500,7751,Katraj,Quick Bites,16,3.3,300.0,Chinese,0,0,0,0,0
19964,500,4113,Magarpatta,Quick Bites,34,3.2,150.0,North Indian,0,0,0,0,0
19965,500,5566,Wadgaon Sheri,Casual Dining,0,0.0,300.0,Biryani,0,0,0,0,0
19966,500,1828,Pimple Saudagar,Quick Bites,65,3.1,550.0,North Indian,0,0,0,0,0
19967,500,9018,SB Road - Aundh,Food Truck,16,3.5,250.0,Fast Food,0,0,0,0,0

In [14]:
rating['loc'] = pd.Categorical(rating['loc'])
rating['loc'] = rating['loc'].cat.codes
rating['sponsor'] = pd.Categorical(rating['sponsor'])
rating['sponsor'] = rating['sponsor'].cat.codes
rating['cuisine'] = pd.Categorical(rating['cuisine'])
rating['cuisine'] = rating['cuisine'].cat.codes

In [15]:
rating

,user_id,index,loc,sponsor,votes,rating,charge,cuisine,alcohol,veg,vegan,sugarfree,buff
0,0,10962,23,22,4,2.8,200.0,69,0,1,0,0,0
1,0,11679,45,22,26,3.6,500.0,59,0,0,0,0,0
2,0,6863,80,24,0,0.0,0.0,8,0,0,0,0,0
3,0,2354,16,6,32,3.4,600.0,19,0,1,0,0,0
4,0,3429,68,22,168,4.3,350.0,66,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19963,500,7751,37,22,16,3.3,300.0,19,0,0,0,0,0
19964,500,4113,53,22,34,3.2,150.0,59,0,0,0,0,0
19965,500,5566,92,6,0,0.0,300.0,13,0,0,0,0,0
19966,500,1828,67,22,65,3.1,550.0,59,0,0,0,0,0
19967,500,9018,74,14,16,3.5,250.0,24,0,0,0,0,0

In [16]:
rating.to_csv('JustTrain.csv')

In [6]:
ratingf = rating.copy()

In [7]:
ratingf = np.array(ratingf)
ratingf

array([[0.0000e+00, 0.0000e+00, 1.0962e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.0000e+00, 0.0000e+00, 1.1679e+04, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [2.0000e+00, 0.0000e+00, 6.8630e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       ...,
       [1.9965e+04, 5.0000e+02, 5.5660e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.9966e+04, 5.0000e+02, 1.8280e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00],
       [1.9967e+04, 5.0000e+02, 9.0180e+03, ..., 0.0000e+00, 0.0000e+00,
        0.0000e+00]])